### ISSUE TITLE
Can't create any form with OC v2.2.11 / Cant open Form Settings 

### ISSUE THREAD

**Issue by chrisvidal** [gromitsoft/oc-forms-plugin#4]
Trying to add a new form is showing an exception
EDIT: and clicking on the form settings throws the same exception

```
htmlspecialchars() expects parameter 1 to be string, array given
```

`in models/form/fields.yaml`

```yaml
        mail_template:
            label: gromit.forms::lang.models.form.fields.mail_template.label
            comment: # set in Form::filterFields
            commentHtml: true
            type: dropdown
            emptyOption: gromit.forms::lang.models.form.fields.mail_template.emptyOption
            tab: gromit.forms::lang.models.form.fields.tab_notifications
```
